/*
 * generated by Xtext
 */
package org.xtext.example.safety.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.safety.services.SafetyGrammarAccess;

public class SafetyParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SafetyGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.safety.parser.antlr.internal.InternalSafetyParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.safety.parser.antlr.internal.InternalSafetyParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Foo";
	}
	
	public SafetyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SafetyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
