/**
 * Copyright (c) 2021, Collins Aerospace.
 * Developed with the sponsorship of Defense Advanced Research Projects Agency (DARPA).
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this data, 
 * including any software or models in source or binary form, as well as any drawings, specifications, 
 * and documentation (collectively "the Data"), to deal in the Data without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Data.
 * 
 * THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 * IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.
 * 
 * Generated by Xtext version 2.25.0.
 */
package edu.umn.cs.crisys.safety.safety;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see edu.umn.cs.crisys.safety.safety.SafetyPackage
 * @generated
 */
public interface SafetyFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SafetyFactory eINSTANCE = edu.umn.cs.crisys.safety.safety.impl.SafetyFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Annex Library</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annex Library</em>'.
   * @generated
   */
  AnnexLibrary createAnnexLibrary();

  /**
   * Returns a new object of class '<em>Annex Subclause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annex Subclause</em>'.
   * @generated
   */
  AnnexSubclause createAnnexSubclause();

  /**
   * Returns a new object of class '<em>Library</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Library</em>'.
   * @generated
   */
  SafetyLibrary createSafetyLibrary();

  /**
   * Returns a new object of class '<em>Subclause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Subclause</em>'.
   * @generated
   */
  SafetySubclause createSafetySubclause();

  /**
   * Returns a new object of class '<em>Contract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract</em>'.
   * @generated
   */
  Contract createContract();

  /**
   * Returns a new object of class '<em>Spec Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Spec Statement</em>'.
   * @generated
   */
  SpecStatement createSpecStatement();

  /**
   * Returns a new object of class '<em>Analysis Behavior</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Analysis Behavior</em>'.
   * @generated
   */
  AnalysisBehavior createAnalysisBehavior();

  /**
   * Returns a new object of class '<em>Fault Subcomponent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fault Subcomponent</em>'.
   * @generated
   */
  FaultSubcomponent createFaultSubcomponent();

  /**
   * Returns a new object of class '<em>HW Fault Subcomponent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>HW Fault Subcomponent</em>'.
   * @generated
   */
  HWFaultSubcomponent createHWFaultSubcomponent();

  /**
   * Returns a new object of class '<em>Propagation Type Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Propagation Type Constraint</em>'.
   * @generated
   */
  PropagationTypeConstraint createPropagationTypeConstraint();

  /**
   * Returns a new object of class '<em>Temporal Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Temporal Constraint</em>'.
   * @generated
   */
  TemporalConstraint createTemporalConstraint();

  /**
   * Returns a new object of class '<em>Trigger Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trigger Condition</em>'.
   * @generated
   */
  TriggerCondition createTriggerCondition();

  /**
   * Returns a new object of class '<em>Eq Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Eq Statement</em>'.
   * @generated
   */
  SafetyEqStatement createSafetyEqStatement();

  /**
   * Returns a new object of class '<em>Interval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interval</em>'.
   * @generated
   */
  SafetyInterval createSafetyInterval();

  /**
   * Returns a new object of class '<em>Contract Library</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Library</em>'.
   * @generated
   */
  SafetyContractLibrary createSafetyContractLibrary();

  /**
   * Returns a new object of class '<em>Contract Subclause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Subclause</em>'.
   * @generated
   */
  SafetyContractSubclause createSafetyContractSubclause();

  /**
   * Returns a new object of class '<em>Contract</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract</em>'.
   * @generated
   */
  SafetyContract createSafetyContract();

  /**
   * Returns a new object of class '<em>Fault Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fault Statement</em>'.
   * @generated
   */
  FaultStatement createFaultStatement();

  /**
   * Returns a new object of class '<em>Analysis Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Analysis Statement</em>'.
   * @generated
   */
  AnalysisStatement createAnalysisStatement();

  /**
   * Returns a new object of class '<em>HW Fault Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>HW Fault Statement</em>'.
   * @generated
   */
  HWFaultStatement createHWFaultStatement();

  /**
   * Returns a new object of class '<em>Propagate Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Propagate Statement</em>'.
   * @generated
   */
  PropagateStatement createPropagateStatement();

  /**
   * Returns a new object of class '<em>Activation Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Activation Statement</em>'.
   * @generated
   */
  ActivationStatement createActivationStatement();

  /**
   * Returns a new object of class '<em>Fault Count Behavior</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fault Count Behavior</em>'.
   * @generated
   */
  FaultCountBehavior createFaultCountBehavior();

  /**
   * Returns a new object of class '<em>Probability Behavior</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Probability Behavior</em>'.
   * @generated
   */
  ProbabilityBehavior createProbabilityBehavior();

  /**
   * Returns a new object of class '<em>Input Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Statement</em>'.
   * @generated
   */
  InputStatement createInputStatement();

  /**
   * Returns a new object of class '<em>Output Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Statement</em>'.
   * @generated
   */
  OutputStatement createOutputStatement();

  /**
   * Returns a new object of class '<em>Duration Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Duration Statement</em>'.
   * @generated
   */
  DurationStatement createDurationStatement();

  /**
   * Returns a new object of class '<em>Probability Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Probability Statement</em>'.
   * @generated
   */
  ProbabilityStatement createProbabilityStatement();

  /**
   * Returns a new object of class '<em>Disable Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Disable Statement</em>'.
   * @generated
   */
  DisableStatement createDisableStatement();

  /**
   * Returns a new object of class '<em>Trigger Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trigger Statement</em>'.
   * @generated
   */
  TriggerStatement createTriggerStatement();

  /**
   * Returns a new object of class '<em>Propagation Type Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Propagation Type Statement</em>'.
   * @generated
   */
  PropagationTypeStatement createPropagationTypeStatement();

  /**
   * Returns a new object of class '<em>asymmetric</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>asymmetric</em>'.
   * @generated
   */
  asymmetric createasymmetric();

  /**
   * Returns a new object of class '<em>symmetric</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>symmetric</em>'.
   * @generated
   */
  symmetric createsymmetric();

  /**
   * Returns a new object of class '<em>Permanent Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Permanent Constraint</em>'.
   * @generated
   */
  PermanentConstraint createPermanentConstraint();

  /**
   * Returns a new object of class '<em>Transient Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transient Constraint</em>'.
   * @generated
   */
  TransientConstraint createTransientConstraint();

  /**
   * Returns a new object of class '<em>Enabler Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enabler Condition</em>'.
   * @generated
   */
  EnablerCondition createEnablerCondition();

  /**
   * Returns a new object of class '<em>Eq Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Eq Value</em>'.
   * @generated
   */
  EqValue createEqValue();

  /**
   * Returns a new object of class '<em>Interval Eq</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interval Eq</em>'.
   * @generated
   */
  IntervalEq createIntervalEq();

  /**
   * Returns a new object of class '<em>Set Eq</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Set Eq</em>'.
   * @generated
   */
  SetEq createSetEq();

  /**
   * Returns a new object of class '<em>Range Eq</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Range Eq</em>'.
   * @generated
   */
  RangeEq createRangeEq();

  /**
   * Returns a new object of class '<em>Closed Safety Interval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Closed Safety Interval</em>'.
   * @generated
   */
  ClosedSafetyInterval createClosedSafetyInterval();

  /**
   * Returns a new object of class '<em>Open Left Safety Interval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Open Left Safety Interval</em>'.
   * @generated
   */
  OpenLeftSafetyInterval createOpenLeftSafetyInterval();

  /**
   * Returns a new object of class '<em>Open Right Safety Interval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Open Right Safety Interval</em>'.
   * @generated
   */
  OpenRightSafetyInterval createOpenRightSafetyInterval();

  /**
   * Returns a new object of class '<em>Open Safety Interval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Open Safety Interval</em>'.
   * @generated
   */
  OpenSafetyInterval createOpenSafetyInterval();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SafetyPackage getSafetyPackage();

} //SafetyFactory
