/*
 * generated by Xtext
 */
package org.xtext.example.safety.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SafetyUiModule extends org.xtext.example.safety.ui.AbstractSafetyUiModule {
	public SafetyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
