/*
 * generated by Xtext
 */
package edu.umn.cs.crisys.safety.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class SafetyProposalProvider extends edu.umn.cs.crisys.safety.ui.contentassist.AbstractSafetyProposalProvider{


//edu.umn.cs.crisys.safety.ui.contentassist.AbstractSafetyProposalProvider {

}
