/*
 * generated by Xtext
 */
package edu.umn.cs.crisys.safety;

import org.eclipse.xtext.generator.IGenerator;

import edu.umn.cs.crisys.safety.generator.NullGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SafetyRuntimeModule extends edu.umn.cs.crisys.safety.AbstractSafetyRuntimeModule {
    public Class<? extends IGenerator> bindIGenerator() {
        return NullGenerator.class;
    }
    
	public Class<? extends org.eclipse.xtext.resource.EObjectAtOffsetHelper> bindEObjectAtOffsetHelper() {
		return org.osate.xtext.aadl2.util.Aadl2EObjectAtOffsetHelper.class;
	}
}
