/*
 * generated by Xtext
 */
package edu.umn.cs.crisys.safety.scoping;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class SafetyScopeProvider extends com.rockwellcollins.atc.agree.scoping.AgreeScopeProvider {

}
