/*
 * generated by Xtext
 */
package edu.umn.cs.crisys.safety.serializer;

import com.google.inject.Inject;
import com.rockwellcollins.atc.agree.agree.AADLEnumerator;
import com.rockwellcollins.atc.agree.agree.AgreeContract;
import com.rockwellcollins.atc.agree.agree.AgreeContractLibrary;
import com.rockwellcollins.atc.agree.agree.AgreeContractSubclause;
import com.rockwellcollins.atc.agree.agree.AgreePackage;
import com.rockwellcollins.atc.agree.agree.AlwaysStatement;
import com.rockwellcollins.atc.agree.agree.Arg;
import com.rockwellcollins.atc.agree.agree.AssertStatement;
import com.rockwellcollins.atc.agree.agree.AssignStatement;
import com.rockwellcollins.atc.agree.agree.AssumeStatement;
import com.rockwellcollins.atc.agree.agree.AsynchStatement;
import com.rockwellcollins.atc.agree.agree.BinaryExpr;
import com.rockwellcollins.atc.agree.agree.BoolLitExpr;
import com.rockwellcollins.atc.agree.agree.CalenStatement;
import com.rockwellcollins.atc.agree.agree.ClosedTimeInterval;
import com.rockwellcollins.atc.agree.agree.ConstStatement;
import com.rockwellcollins.atc.agree.agree.EnumStatement;
import com.rockwellcollins.atc.agree.agree.EqStatement;
import com.rockwellcollins.atc.agree.agree.EventExpr;
import com.rockwellcollins.atc.agree.agree.FloorCast;
import com.rockwellcollins.atc.agree.agree.FnCallExpr;
import com.rockwellcollins.atc.agree.agree.FnDefExpr;
import com.rockwellcollins.atc.agree.agree.GetPropertyExpr;
import com.rockwellcollins.atc.agree.agree.GuaranteeStatement;
import com.rockwellcollins.atc.agree.agree.IfThenElseExpr;
import com.rockwellcollins.atc.agree.agree.InputStatement;
import com.rockwellcollins.atc.agree.agree.IntLitExpr;
import com.rockwellcollins.atc.agree.agree.LatchedExpr;
import com.rockwellcollins.atc.agree.agree.LatchedStatement;
import com.rockwellcollins.atc.agree.agree.LemmaStatement;
import com.rockwellcollins.atc.agree.agree.LibraryFnDefExpr;
import com.rockwellcollins.atc.agree.agree.LinearizationDefExpr;
import com.rockwellcollins.atc.agree.agree.LinearizationInterval;
import com.rockwellcollins.atc.agree.agree.MNSynchStatement;
import com.rockwellcollins.atc.agree.agree.NamedID;
import com.rockwellcollins.atc.agree.agree.NestedDotID;
import com.rockwellcollins.atc.agree.agree.NodeBodyExpr;
import com.rockwellcollins.atc.agree.agree.NodeDefExpr;
import com.rockwellcollins.atc.agree.agree.NodeEq;
import com.rockwellcollins.atc.agree.agree.NodeLemma;
import com.rockwellcollins.atc.agree.agree.OpenLeftTimeInterval;
import com.rockwellcollins.atc.agree.agree.OpenRightTimeInterval;
import com.rockwellcollins.atc.agree.agree.OpenTimeInterval;
import com.rockwellcollins.atc.agree.agree.OrderStatement;
import com.rockwellcollins.atc.agree.agree.PeriodicStatement;
import com.rockwellcollins.atc.agree.agree.PreExpr;
import com.rockwellcollins.atc.agree.agree.PrevExpr;
import com.rockwellcollins.atc.agree.agree.PrimType;
import com.rockwellcollins.atc.agree.agree.PropertyStatement;
import com.rockwellcollins.atc.agree.agree.RealCast;
import com.rockwellcollins.atc.agree.agree.RealLitExpr;
import com.rockwellcollins.atc.agree.agree.RecordDefExpr;
import com.rockwellcollins.atc.agree.agree.RecordExpr;
import com.rockwellcollins.atc.agree.agree.RecordType;
import com.rockwellcollins.atc.agree.agree.RecordUpdateExpr;
import com.rockwellcollins.atc.agree.agree.SporadicStatement;
import com.rockwellcollins.atc.agree.agree.SynchStatement;
import com.rockwellcollins.atc.agree.agree.ThisExpr;
import com.rockwellcollins.atc.agree.agree.TimeExpr;
import com.rockwellcollins.atc.agree.agree.TimeFallExpr;
import com.rockwellcollins.atc.agree.agree.TimeOfExpr;
import com.rockwellcollins.atc.agree.agree.TimeRiseExpr;
import com.rockwellcollins.atc.agree.agree.TypeID;
import com.rockwellcollins.atc.agree.agree.UnaryExpr;
import com.rockwellcollins.atc.agree.agree.WhenHoldsStatement;
import com.rockwellcollins.atc.agree.agree.WhenOccursStatment;
import com.rockwellcollins.atc.agree.agree.WheneverBecomesTrueStatement;
import com.rockwellcollins.atc.agree.agree.WheneverHoldsStatement;
import com.rockwellcollins.atc.agree.agree.WheneverImpliesStatement;
import com.rockwellcollins.atc.agree.agree.WheneverOccursStatement;
import com.rockwellcollins.atc.agree.serializer.AgreeSemanticSequencer;
import edu.umn.cs.crisys.safety.safety.AnalysisStatement;
import edu.umn.cs.crisys.safety.safety.ClosedInterval;
import edu.umn.cs.crisys.safety.safety.DurationStatement;
import edu.umn.cs.crisys.safety.safety.EnablerCondition;
import edu.umn.cs.crisys.safety.safety.EqValue;
import edu.umn.cs.crisys.safety.safety.FaultCountBehavior;
import edu.umn.cs.crisys.safety.safety.FaultStatement;
import edu.umn.cs.crisys.safety.safety.HWFaultStatement;
import edu.umn.cs.crisys.safety.safety.IntervalEq;
import edu.umn.cs.crisys.safety.safety.OpenInterval;
import edu.umn.cs.crisys.safety.safety.OpenLeftInterval;
import edu.umn.cs.crisys.safety.safety.OpenRightInterval;
import edu.umn.cs.crisys.safety.safety.OutputStatement;
import edu.umn.cs.crisys.safety.safety.PermanentConstraint;
import edu.umn.cs.crisys.safety.safety.ProbabilityBehavior;
import edu.umn.cs.crisys.safety.safety.ProbabilityStatement;
import edu.umn.cs.crisys.safety.safety.PropagateStatement;
import edu.umn.cs.crisys.safety.safety.PropagationTypeStatement;
import edu.umn.cs.crisys.safety.safety.RangeEq;
import edu.umn.cs.crisys.safety.safety.SafetyContract;
import edu.umn.cs.crisys.safety.safety.SafetyContractLibrary;
import edu.umn.cs.crisys.safety.safety.SafetyContractSubclause;
import edu.umn.cs.crisys.safety.safety.SafetyPackage;
import edu.umn.cs.crisys.safety.safety.SetEq;
import edu.umn.cs.crisys.safety.safety.TransientConstraint;
import edu.umn.cs.crisys.safety.safety.TriggerStatement;
import edu.umn.cs.crisys.safety.safety.asymmetric;
import edu.umn.cs.crisys.safety.safety.symmetric;
import edu.umn.cs.crisys.safety.services.SafetyGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.osate.aadl2.Aadl2Package;
import org.osate.aadl2.ArrayRange;
import org.osate.aadl2.BasicPropertyAssociation;
import org.osate.aadl2.BooleanLiteral;
import org.osate.aadl2.ClassifierValue;
import org.osate.aadl2.ComputedValue;
import org.osate.aadl2.ContainedNamedElement;
import org.osate.aadl2.ContainmentPathElement;
import org.osate.aadl2.IntegerLiteral;
import org.osate.aadl2.ListValue;
import org.osate.aadl2.ModalPropertyValue;
import org.osate.aadl2.NamedValue;
import org.osate.aadl2.Operation;
import org.osate.aadl2.PropertyAssociation;
import org.osate.aadl2.RangeValue;
import org.osate.aadl2.RealLiteral;
import org.osate.aadl2.RecordValue;
import org.osate.aadl2.ReferenceValue;
import org.osate.aadl2.StringLiteral;

@SuppressWarnings("all")
public abstract class AbstractSafetySemanticSequencer extends AgreeSemanticSequencer {

	@Inject
	private SafetyGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == Aadl2Package.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case Aadl2Package.ARRAY_RANGE:
				sequence_ArrayRange(context, (ArrayRange) semanticObject); 
				return; 
			case Aadl2Package.BASIC_PROPERTY_ASSOCIATION:
				sequence_FieldPropertyAssociation(context, (BasicPropertyAssociation) semanticObject); 
				return; 
			case Aadl2Package.BOOLEAN_LITERAL:
				sequence_BooleanLiteral(context, (BooleanLiteral) semanticObject); 
				return; 
			case Aadl2Package.CLASSIFIER_VALUE:
				sequence_ComponentClassifierTerm(context, (ClassifierValue) semanticObject); 
				return; 
			case Aadl2Package.COMPUTED_VALUE:
				sequence_ComputedTerm(context, (ComputedValue) semanticObject); 
				return; 
			case Aadl2Package.CONTAINED_NAMED_ELEMENT:
				sequence_ContainmentPath(context, (ContainedNamedElement) semanticObject); 
				return; 
			case Aadl2Package.CONTAINMENT_PATH_ELEMENT:
				sequence_ContainmentPathElement(context, (ContainmentPathElement) semanticObject); 
				return; 
			case Aadl2Package.INTEGER_LITERAL:
				sequence_IntegerTerm(context, (IntegerLiteral) semanticObject); 
				return; 
			case Aadl2Package.LIST_VALUE:
				sequence_ListTerm(context, (ListValue) semanticObject); 
				return; 
			case Aadl2Package.MODAL_PROPERTY_VALUE:
				if (rule == grammarAccess.getModalPropertyValueRule()) {
					sequence_ModalPropertyValue(context, (ModalPropertyValue) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getOptionalModalPropertyValueRule()) {
					sequence_OptionalModalPropertyValue(context, (ModalPropertyValue) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getPropertyValueRule()) {
					sequence_PropertyValue(context, (ModalPropertyValue) semanticObject); 
					return; 
				}
				else break;
			case Aadl2Package.NAMED_VALUE:
				if (rule == grammarAccess.getConstantValueRule()
						|| rule == grammarAccess.getNumAltRule()) {
					sequence_ConstantValue(context, (NamedValue) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getPropertyExpressionRule()
						|| rule == grammarAccess.getLiteralorReferenceTermRule()) {
					sequence_LiteralorReferenceTerm(context, (NamedValue) semanticObject); 
					return; 
				}
				else break;
			case Aadl2Package.OPERATION:
				sequence_SignedConstant(context, (Operation) semanticObject); 
				return; 
			case Aadl2Package.PROPERTY_ASSOCIATION:
				if (rule == grammarAccess.getBasicPropertyAssociationRule()) {
					sequence_BasicPropertyAssociation(context, (PropertyAssociation) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getPModelRule()
						|| rule == grammarAccess.getContainedPropertyAssociationRule()) {
					sequence_ContainedPropertyAssociation(context, (PropertyAssociation) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getPropertyAssociationRule()) {
					sequence_PropertyAssociation(context, (PropertyAssociation) semanticObject); 
					return; 
				}
				else break;
			case Aadl2Package.RANGE_VALUE:
				sequence_NumericRangeTerm(context, (RangeValue) semanticObject); 
				return; 
			case Aadl2Package.REAL_LITERAL:
				sequence_RealTerm(context, (RealLiteral) semanticObject); 
				return; 
			case Aadl2Package.RECORD_VALUE:
				if (rule == grammarAccess.getOldRecordTermRule()) {
					sequence_OldRecordTerm(context, (RecordValue) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getPropertyExpressionRule()
						|| rule == grammarAccess.getRecordTermRule()) {
					sequence_RecordTerm(context, (RecordValue) semanticObject); 
					return; 
				}
				else break;
			case Aadl2Package.REFERENCE_VALUE:
				sequence_ReferenceTerm(context, (ReferenceValue) semanticObject); 
				return; 
			case Aadl2Package.STRING_LITERAL:
				sequence_StringTerm(context, (StringLiteral) semanticObject); 
				return; 
			}
		else if (epackage == AgreePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case AgreePackage.AADL_ENUMERATOR:
				sequence_TermExpr(context, (AADLEnumerator) semanticObject); 
				return; 
			case AgreePackage.AGREE_CONTRACT:
				sequence_AgreeContract(context, (AgreeContract) semanticObject); 
				return; 
			case AgreePackage.AGREE_CONTRACT_LIBRARY:
				sequence_AgreeLibrary(context, (AgreeContractLibrary) semanticObject); 
				return; 
			case AgreePackage.AGREE_CONTRACT_SUBCLAUSE:
				sequence_AgreeSubclause(context, (AgreeContractSubclause) semanticObject); 
				return; 
			case AgreePackage.ALWAYS_STATEMENT:
				sequence_PatternStatement(context, (AlwaysStatement) semanticObject); 
				return; 
			case AgreePackage.ARG:
				sequence_Arg(context, (Arg) semanticObject); 
				return; 
			case AgreePackage.ASSERT_STATEMENT:
				sequence_NamedSpecStatement(context, (AssertStatement) semanticObject); 
				return; 
			case AgreePackage.ASSIGN_STATEMENT:
				sequence_AssignStatement(context, (AssignStatement) semanticObject); 
				return; 
			case AgreePackage.ASSUME_STATEMENT:
				sequence_NamedSpecStatement(context, (AssumeStatement) semanticObject); 
				return; 
			case AgreePackage.ASYNCH_STATEMENT:
				sequence_SynchStatement(context, (AsynchStatement) semanticObject); 
				return; 
			case AgreePackage.BINARY_EXPR:
				sequence_AddSubExpr_AndExpr_ArrowExpr_EquivExpr_ImpliesExpr_MultDivExpr_OrExpr_PowerExpr_RelateExpr(context, (BinaryExpr) semanticObject); 
				return; 
			case AgreePackage.BOOL_LIT_EXPR:
				sequence_TermExpr(context, (BoolLitExpr) semanticObject); 
				return; 
			case AgreePackage.CALEN_STATEMENT:
				sequence_SynchStatement(context, (CalenStatement) semanticObject); 
				return; 
			case AgreePackage.CLOSED_TIME_INTERVAL:
				sequence_TimeInterval(context, (ClosedTimeInterval) semanticObject); 
				return; 
			case AgreePackage.CONST_STATEMENT:
				sequence_ConstStatement(context, (ConstStatement) semanticObject); 
				return; 
			case AgreePackage.ENUM_STATEMENT:
				sequence_EnumStatement(context, (EnumStatement) semanticObject); 
				return; 
			case AgreePackage.EQ_STATEMENT:
				sequence_EqStatement(context, (EqStatement) semanticObject); 
				return; 
			case AgreePackage.EVENT_EXPR:
				sequence_TermExpr(context, (EventExpr) semanticObject); 
				return; 
			case AgreePackage.FLOOR_CAST:
				sequence_TermExpr(context, (FloorCast) semanticObject); 
				return; 
			case AgreePackage.FN_CALL_EXPR:
				sequence_ComplexExpr(context, (FnCallExpr) semanticObject); 
				return; 
			case AgreePackage.FN_DEF_EXPR:
				sequence_FnDefExpr(context, (FnDefExpr) semanticObject); 
				return; 
			case AgreePackage.GET_PROPERTY_EXPR:
				sequence_PreDefFnExpr(context, (GetPropertyExpr) semanticObject); 
				return; 
			case AgreePackage.GUARANTEE_STATEMENT:
				sequence_NamedSpecStatement(context, (GuaranteeStatement) semanticObject); 
				return; 
			case AgreePackage.IF_THEN_ELSE_EXPR:
				sequence_IfThenElseExpr(context, (IfThenElseExpr) semanticObject); 
				return; 
			case AgreePackage.INPUT_STATEMENT:
				sequence_InputStatement(context, (InputStatement) semanticObject); 
				return; 
			case AgreePackage.INT_LIT_EXPR:
				sequence_TermExpr(context, (IntLitExpr) semanticObject); 
				return; 
			case AgreePackage.LATCHED_EXPR:
				sequence_TermExpr(context, (LatchedExpr) semanticObject); 
				return; 
			case AgreePackage.LATCHED_STATEMENT:
				sequence_SynchStatement(context, (LatchedStatement) semanticObject); 
				return; 
			case AgreePackage.LEMMA_STATEMENT:
				sequence_NamedSpecStatement(context, (LemmaStatement) semanticObject); 
				return; 
			case AgreePackage.LIBRARY_FN_DEF_EXPR:
				sequence_LibraryFnDefExpr(context, (LibraryFnDefExpr) semanticObject); 
				return; 
			case AgreePackage.LINEARIZATION_DEF_EXPR:
				sequence_LinearizationDefExpr(context, (LinearizationDefExpr) semanticObject); 
				return; 
			case AgreePackage.LINEARIZATION_INTERVAL:
				sequence_LinearizationInterval(context, (LinearizationInterval) semanticObject); 
				return; 
			case AgreePackage.MN_SYNCH_STATEMENT:
				sequence_SynchStatement(context, (MNSynchStatement) semanticObject); 
				return; 
			case AgreePackage.NAMED_ID:
				sequence_NamedID(context, (NamedID) semanticObject); 
				return; 
			case AgreePackage.NESTED_DOT_ID:
				sequence_NestedDotID(context, (NestedDotID) semanticObject); 
				return; 
			case AgreePackage.NODE_BODY_EXPR:
				sequence_NodeBodyExpr(context, (NodeBodyExpr) semanticObject); 
				return; 
			case AgreePackage.NODE_DEF_EXPR:
				sequence_NodeDefExpr(context, (NodeDefExpr) semanticObject); 
				return; 
			case AgreePackage.NODE_EQ:
				sequence_NodeStmt(context, (NodeEq) semanticObject); 
				return; 
			case AgreePackage.NODE_LEMMA:
				sequence_NodeStmt(context, (NodeLemma) semanticObject); 
				return; 
			case AgreePackage.OPEN_LEFT_TIME_INTERVAL:
				sequence_TimeInterval(context, (OpenLeftTimeInterval) semanticObject); 
				return; 
			case AgreePackage.OPEN_RIGHT_TIME_INTERVAL:
				sequence_TimeInterval(context, (OpenRightTimeInterval) semanticObject); 
				return; 
			case AgreePackage.OPEN_TIME_INTERVAL:
				sequence_TimeInterval(context, (OpenTimeInterval) semanticObject); 
				return; 
			case AgreePackage.ORDER_STATEMENT:
				sequence_OrderStatement(context, (OrderStatement) semanticObject); 
				return; 
			case AgreePackage.PERIODIC_STATEMENT:
				sequence_RealTimeStatement(context, (PeriodicStatement) semanticObject); 
				return; 
			case AgreePackage.PRE_EXPR:
				sequence_TermExpr(context, (PreExpr) semanticObject); 
				return; 
			case AgreePackage.PREV_EXPR:
				sequence_PreDefFnExpr(context, (PrevExpr) semanticObject); 
				return; 
			case AgreePackage.PRIM_TYPE:
				sequence_Type(context, (PrimType) semanticObject); 
				return; 
			case AgreePackage.PROPERTY_STATEMENT:
				sequence_PropertyStatement(context, (PropertyStatement) semanticObject); 
				return; 
			case AgreePackage.REAL_CAST:
				sequence_TermExpr(context, (RealCast) semanticObject); 
				return; 
			case AgreePackage.REAL_LIT_EXPR:
				sequence_TermExpr(context, (RealLitExpr) semanticObject); 
				return; 
			case AgreePackage.RECORD_DEF_EXPR:
				sequence_RecordDefExpr(context, (RecordDefExpr) semanticObject); 
				return; 
			case AgreePackage.RECORD_EXPR:
				sequence_ComplexExpr(context, (RecordExpr) semanticObject); 
				return; 
			case AgreePackage.RECORD_TYPE:
				sequence_Type(context, (RecordType) semanticObject); 
				return; 
			case AgreePackage.RECORD_UPDATE_EXPR:
				sequence_RecordUpdateExpr(context, (RecordUpdateExpr) semanticObject); 
				return; 
			case AgreePackage.SPORADIC_STATEMENT:
				sequence_RealTimeStatement(context, (SporadicStatement) semanticObject); 
				return; 
			case AgreePackage.SYNCH_STATEMENT:
				sequence_SynchStatement(context, (SynchStatement) semanticObject); 
				return; 
			case AgreePackage.THIS_EXPR:
				sequence_TermExpr(context, (ThisExpr) semanticObject); 
				return; 
			case AgreePackage.TIME_EXPR:
				sequence_TermExpr(context, (TimeExpr) semanticObject); 
				return; 
			case AgreePackage.TIME_FALL_EXPR:
				sequence_TermExpr(context, (TimeFallExpr) semanticObject); 
				return; 
			case AgreePackage.TIME_OF_EXPR:
				sequence_TermExpr(context, (TimeOfExpr) semanticObject); 
				return; 
			case AgreePackage.TIME_RISE_EXPR:
				sequence_TermExpr(context, (TimeRiseExpr) semanticObject); 
				return; 
			case AgreePackage.TYPE_ID:
				sequence_TypeID(context, (TypeID) semanticObject); 
				return; 
			case AgreePackage.UNARY_EXPR:
				sequence_UnaryExpr(context, (UnaryExpr) semanticObject); 
				return; 
			case AgreePackage.WHEN_HOLDS_STATEMENT:
				sequence_WhenStatement(context, (WhenHoldsStatement) semanticObject); 
				return; 
			case AgreePackage.WHEN_OCCURS_STATMENT:
				sequence_WhenStatement(context, (WhenOccursStatment) semanticObject); 
				return; 
			case AgreePackage.WHENEVER_BECOMES_TRUE_STATEMENT:
				sequence_WheneverStatement(context, (WheneverBecomesTrueStatement) semanticObject); 
				return; 
			case AgreePackage.WHENEVER_HOLDS_STATEMENT:
				sequence_WheneverStatement(context, (WheneverHoldsStatement) semanticObject); 
				return; 
			case AgreePackage.WHENEVER_IMPLIES_STATEMENT:
				sequence_WheneverStatement(context, (WheneverImpliesStatement) semanticObject); 
				return; 
			case AgreePackage.WHENEVER_OCCURS_STATEMENT:
				sequence_WheneverStatement(context, (WheneverOccursStatement) semanticObject); 
				return; 
			}
		else if (epackage == SafetyPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SafetyPackage.ANALYSIS_STATEMENT:
				sequence_SpecStatement(context, (AnalysisStatement) semanticObject); 
				return; 
			case SafetyPackage.CLOSED_INTERVAL:
				sequence_Interval(context, (ClosedInterval) semanticObject); 
				return; 
			case SafetyPackage.DURATION_STATEMENT:
				if (rule == grammarAccess.getElementSafetyRule()
						|| rule == grammarAccess.getFaultSubcomponentRule()) {
					sequence_FaultSubcomponent(context, (DurationStatement) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getHWFaultSubcomponentRule()) {
					sequence_HWFaultSubcomponent(context, (DurationStatement) semanticObject); 
					return; 
				}
				else break;
			case SafetyPackage.ENABLER_CONDITION:
				sequence_TriggerCondition(context, (EnablerCondition) semanticObject); 
				return; 
			case SafetyPackage.EQ_VALUE:
				sequence_SafetyEqStatement(context, (EqValue) semanticObject); 
				return; 
			case SafetyPackage.FAULT_COUNT_BEHAVIOR:
				sequence_AnalysisBehavior(context, (FaultCountBehavior) semanticObject); 
				return; 
			case SafetyPackage.FAULT_STATEMENT:
				sequence_SpecStatement(context, (FaultStatement) semanticObject); 
				return; 
			case SafetyPackage.HW_FAULT_STATEMENT:
				sequence_SpecStatement(context, (HWFaultStatement) semanticObject); 
				return; 
			case SafetyPackage.INPUT_STATEMENT:
				sequence_FaultSubcomponent(context, (edu.umn.cs.crisys.safety.safety.InputStatement) semanticObject); 
				return; 
			case SafetyPackage.INTERVAL_EQ:
				sequence_SafetyEqStatement(context, (IntervalEq) semanticObject); 
				return; 
			case SafetyPackage.OPEN_INTERVAL:
				sequence_Interval(context, (OpenInterval) semanticObject); 
				return; 
			case SafetyPackage.OPEN_LEFT_INTERVAL:
				sequence_Interval(context, (OpenLeftInterval) semanticObject); 
				return; 
			case SafetyPackage.OPEN_RIGHT_INTERVAL:
				sequence_Interval(context, (OpenRightInterval) semanticObject); 
				return; 
			case SafetyPackage.OUTPUT_STATEMENT:
				sequence_FaultSubcomponent(context, (OutputStatement) semanticObject); 
				return; 
			case SafetyPackage.PERMANENT_CONSTRAINT:
				sequence_TemporalConstraint(context, (PermanentConstraint) semanticObject); 
				return; 
			case SafetyPackage.PROBABILITY_BEHAVIOR:
				sequence_AnalysisBehavior(context, (ProbabilityBehavior) semanticObject); 
				return; 
			case SafetyPackage.PROBABILITY_STATEMENT:
				if (rule == grammarAccess.getElementSafetyRule()
						|| rule == grammarAccess.getFaultSubcomponentRule()) {
					sequence_FaultSubcomponent(context, (ProbabilityStatement) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getHWFaultSubcomponentRule()) {
					sequence_HWFaultSubcomponent(context, (ProbabilityStatement) semanticObject); 
					return; 
				}
				else break;
			case SafetyPackage.PROPAGATE_STATEMENT:
				sequence_SpecStatement(context, (PropagateStatement) semanticObject); 
				return; 
			case SafetyPackage.PROPAGATION_TYPE_STATEMENT:
				if (rule == grammarAccess.getElementSafetyRule()
						|| rule == grammarAccess.getFaultSubcomponentRule()) {
					sequence_FaultSubcomponent(context, (PropagationTypeStatement) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getHWFaultSubcomponentRule()) {
					sequence_HWFaultSubcomponent(context, (PropagationTypeStatement) semanticObject); 
					return; 
				}
				else break;
			case SafetyPackage.RANGE_EQ:
				sequence_SafetyEqStatement(context, (RangeEq) semanticObject); 
				return; 
			case SafetyPackage.SAFETY_CONTRACT:
				sequence_SafetyContract(context, (SafetyContract) semanticObject); 
				return; 
			case SafetyPackage.SAFETY_CONTRACT_LIBRARY:
				sequence_SafetyLibrary(context, (SafetyContractLibrary) semanticObject); 
				return; 
			case SafetyPackage.SAFETY_CONTRACT_SUBCLAUSE:
				sequence_SafetySubclause(context, (SafetyContractSubclause) semanticObject); 
				return; 
			case SafetyPackage.SET_EQ:
				sequence_SafetyEqStatement(context, (SetEq) semanticObject); 
				return; 
			case SafetyPackage.TRANSIENT_CONSTRAINT:
				sequence_TemporalConstraint(context, (TransientConstraint) semanticObject); 
				return; 
			case SafetyPackage.TRIGGER_STATEMENT:
				sequence_FaultSubcomponent(context, (TriggerStatement) semanticObject); 
				return; 
			case SafetyPackage.ASYMMETRIC:
				sequence_PropagationTypeConstraint(context, (asymmetric) semanticObject); 
				return; 
			case SafetyPackage.SYMMETRIC:
				sequence_PropagationTypeConstraint(context, (symmetric) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     AnalysisBehavior returns FaultCountBehavior
	 *
	 * Constraint:
	 *     maxFaults=INTEGER_LIT
	 */
	protected void sequence_AnalysisBehavior(ISerializationContext context, FaultCountBehavior semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.FAULT_COUNT_BEHAVIOR__MAX_FAULTS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.FAULT_COUNT_BEHAVIOR__MAX_FAULTS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAnalysisBehaviorAccess().getMaxFaultsINTEGER_LITTerminalRuleCall_0_2_0(), semanticObject.getMaxFaults());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AnalysisBehavior returns ProbabilityBehavior
	 *
	 * Constraint:
	 *     probabilty=REAL_LIT
	 */
	protected void sequence_AnalysisBehavior(ISerializationContext context, ProbabilityBehavior semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.PROBABILITY_BEHAVIOR__PROBABILTY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.PROBABILITY_BEHAVIOR__PROBABILTY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAnalysisBehaviorAccess().getProbabiltyREAL_LITTerminalRuleCall_1_2_0(), semanticObject.getProbabilty());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns DurationStatement
	 *     FaultSubcomponent returns DurationStatement
	 *
	 * Constraint:
	 *     (tc=TemporalConstraint interv=Interval?)
	 */
	protected void sequence_FaultSubcomponent(ISerializationContext context, DurationStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns InputStatement
	 *     FaultSubcomponent returns InputStatement
	 *
	 * Constraint:
	 *     (fault_in+=ID nom_conn+=Expr (fault_in+=ID nom_conn+=Expr)*)
	 */
	protected void sequence_FaultSubcomponent(ISerializationContext context, edu.umn.cs.crisys.safety.safety.InputStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns OutputStatement
	 *     FaultSubcomponent returns OutputStatement
	 *
	 * Constraint:
	 *     (nom_conn+=NestedDotID fault_out+=ID (nom_conn+=NestedDotID fault_out+=ID)*)
	 */
	protected void sequence_FaultSubcomponent(ISerializationContext context, OutputStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns ProbabilityStatement
	 *     FaultSubcomponent returns ProbabilityStatement
	 *
	 * Constraint:
	 *     probability=REAL_LIT
	 */
	protected void sequence_FaultSubcomponent(ISerializationContext context, ProbabilityStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.PROBABILITY_STATEMENT__PROBABILITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.PROBABILITY_STATEMENT__PROBABILITY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFaultSubcomponentAccess().getProbabilityREAL_LITTerminalRuleCall_3_3_0(), semanticObject.getProbability());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns PropagationTypeStatement
	 *     FaultSubcomponent returns PropagationTypeStatement
	 *
	 * Constraint:
	 *     pty=PropagationTypeConstraint
	 */
	protected void sequence_FaultSubcomponent(ISerializationContext context, PropagationTypeStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.PROPAGATION_TYPE_STATEMENT__PTY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.PROPAGATION_TYPE_STATEMENT__PTY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFaultSubcomponentAccess().getPtyPropagationTypeConstraintParserRuleCall_5_3_0(), semanticObject.getPty());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns TriggerStatement
	 *     FaultSubcomponent returns TriggerStatement
	 *
	 * Constraint:
	 *     cond=TriggerCondition
	 */
	protected void sequence_FaultSubcomponent(ISerializationContext context, TriggerStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.TRIGGER_STATEMENT__COND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.TRIGGER_STATEMENT__COND));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFaultSubcomponentAccess().getCondTriggerConditionParserRuleCall_4_2_0(), semanticObject.getCond());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     HWFaultSubcomponent returns DurationStatement
	 *
	 * Constraint:
	 *     (tc=TemporalConstraint interv=Interval?)
	 */
	protected void sequence_HWFaultSubcomponent(ISerializationContext context, DurationStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     HWFaultSubcomponent returns ProbabilityStatement
	 *
	 * Constraint:
	 *     probability=REAL_LIT
	 */
	protected void sequence_HWFaultSubcomponent(ISerializationContext context, ProbabilityStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.PROBABILITY_STATEMENT__PROBABILITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.PROBABILITY_STATEMENT__PROBABILITY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getHWFaultSubcomponentAccess().getProbabilityREAL_LITTerminalRuleCall_1_3_0(), semanticObject.getProbability());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     HWFaultSubcomponent returns PropagationTypeStatement
	 *
	 * Constraint:
	 *     pty=PropagationTypeConstraint
	 */
	protected void sequence_HWFaultSubcomponent(ISerializationContext context, PropagationTypeStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.PROPAGATION_TYPE_STATEMENT__PTY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.PROPAGATION_TYPE_STATEMENT__PTY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getHWFaultSubcomponentAccess().getPtyPropagationTypeConstraintParserRuleCall_2_3_0(), semanticObject.getPty());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Interval returns ClosedInterval
	 *
	 * Constraint:
	 *     (low=Expr high=Expr)
	 */
	protected void sequence_Interval(ISerializationContext context, ClosedInterval semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL__LOW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL__LOW));
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL__HIGH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL__HIGH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntervalAccess().getLowExprParserRuleCall_0_0_2_0(), semanticObject.getLow());
		feeder.accept(grammarAccess.getIntervalAccess().getHighExprParserRuleCall_0_0_4_0(), semanticObject.getHigh());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Interval returns OpenInterval
	 *
	 * Constraint:
	 *     (low=Expr high=Expr)
	 */
	protected void sequence_Interval(ISerializationContext context, OpenInterval semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL__LOW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL__LOW));
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL__HIGH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL__HIGH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntervalAccess().getLowExprParserRuleCall_3_0_2_0(), semanticObject.getLow());
		feeder.accept(grammarAccess.getIntervalAccess().getHighExprParserRuleCall_3_0_4_0(), semanticObject.getHigh());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Interval returns OpenLeftInterval
	 *
	 * Constraint:
	 *     (low=Expr high=Expr)
	 */
	protected void sequence_Interval(ISerializationContext context, OpenLeftInterval semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL__LOW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL__LOW));
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL__HIGH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL__HIGH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntervalAccess().getLowExprParserRuleCall_1_0_2_0(), semanticObject.getLow());
		feeder.accept(grammarAccess.getIntervalAccess().getHighExprParserRuleCall_1_0_4_0(), semanticObject.getHigh());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Interval returns OpenRightInterval
	 *
	 * Constraint:
	 *     (low=Expr high=Expr)
	 */
	protected void sequence_Interval(ISerializationContext context, OpenRightInterval semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL__LOW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL__LOW));
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL__HIGH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL__HIGH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntervalAccess().getLowExprParserRuleCall_2_0_2_0(), semanticObject.getLow());
		feeder.accept(grammarAccess.getIntervalAccess().getHighExprParserRuleCall_2_0_4_0(), semanticObject.getHigh());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     PropagationTypeConstraint returns asymmetric
	 *
	 * Constraint:
	 *     {asymmetric}
	 */
	protected void sequence_PropagationTypeConstraint(ISerializationContext context, asymmetric semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PropagationTypeConstraint returns symmetric
	 *
	 * Constraint:
	 *     {symmetric}
	 */
	protected void sequence_PropagationTypeConstraint(ISerializationContext context, symmetric semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SafetyContract returns SafetyContract
	 *
	 * Constraint:
	 *     specs+=SpecStatement*
	 */
	protected void sequence_SafetyContract(ISerializationContext context, SafetyContract semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns EqValue
	 *     FaultSubcomponent returns EqValue
	 *     SafetyEqStatement returns EqValue
	 *
	 * Constraint:
	 *     (lhs+=Arg lhs+=Arg* expr=Expr?)
	 */
	protected void sequence_SafetyEqStatement(ISerializationContext context, EqValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns IntervalEq
	 *     FaultSubcomponent returns IntervalEq
	 *     SafetyEqStatement returns IntervalEq
	 *
	 * Constraint:
	 *     (lhs_int=Arg interv=Interval)
	 */
	protected void sequence_SafetyEqStatement(ISerializationContext context, IntervalEq semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL_EQ__LHS_INT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL_EQ__LHS_INT));
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.INTERVAL_EQ__INTERV) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.INTERVAL_EQ__INTERV));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSafetyEqStatementAccess().getLhs_intArgParserRuleCall_1_2_0(), semanticObject.getLhs_int());
		feeder.accept(grammarAccess.getSafetyEqStatementAccess().getIntervIntervalParserRuleCall_1_4_0(), semanticObject.getInterv());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns RangeEq
	 *     FaultSubcomponent returns RangeEq
	 *     SafetyEqStatement returns RangeEq
	 *
	 * Constraint:
	 *     (lhs_range=Arg l1=Expr l2=Expr)
	 */
	protected void sequence_SafetyEqStatement(ISerializationContext context, RangeEq semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.RANGE_EQ__LHS_RANGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.RANGE_EQ__LHS_RANGE));
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.RANGE_EQ__L1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.RANGE_EQ__L1));
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.RANGE_EQ__L2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.RANGE_EQ__L2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSafetyEqStatementAccess().getLhs_rangeArgParserRuleCall_3_2_0(), semanticObject.getLhs_range());
		feeder.accept(grammarAccess.getSafetyEqStatementAccess().getL1ExprParserRuleCall_3_5_0(), semanticObject.getL1());
		feeder.accept(grammarAccess.getSafetyEqStatementAccess().getL2ExprParserRuleCall_3_7_0(), semanticObject.getL2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ElementSafety returns SetEq
	 *     FaultSubcomponent returns SetEq
	 *     SafetyEqStatement returns SetEq
	 *
	 * Constraint:
	 *     (lhs_set=Arg l1=Expr list+=Expr*)
	 */
	protected void sequence_SafetyEqStatement(ISerializationContext context, SetEq semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AnnexLibrary returns SafetyContractLibrary
	 *     SafetyLibrary returns SafetyContractLibrary
	 *
	 * Constraint:
	 *     contract=SafetyContract
	 */
	protected void sequence_SafetyLibrary(ISerializationContext context, SafetyContractLibrary semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.SAFETY_CONTRACT_LIBRARY__CONTRACT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.SAFETY_CONTRACT_LIBRARY__CONTRACT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSafetyLibraryAccess().getContractSafetyContractParserRuleCall_1_0(), semanticObject.getContract());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AnnexSubclause returns SafetyContractSubclause
	 *     SafetySubclause returns SafetyContractSubclause
	 *
	 * Constraint:
	 *     contract=SafetyContract
	 */
	protected void sequence_SafetySubclause(ISerializationContext context, SafetyContractSubclause semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.SAFETY_CONTRACT_SUBCLAUSE__CONTRACT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.SAFETY_CONTRACT_SUBCLAUSE__CONTRACT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSafetySubclauseAccess().getContractSafetyContractParserRuleCall_1_0(), semanticObject.getContract());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SpecStatement returns AnalysisStatement
	 *     Element returns AnalysisStatement
	 *
	 * Constraint:
	 *     behavior=AnalysisBehavior
	 */
	protected void sequence_SpecStatement(ISerializationContext context, AnalysisStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SafetyPackage.Literals.ANALYSIS_STATEMENT__BEHAVIOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SafetyPackage.Literals.ANALYSIS_STATEMENT__BEHAVIOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSpecStatementAccess().getBehaviorAnalysisBehaviorParserRuleCall_1_3_0(), semanticObject.getBehavior());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SpecStatement returns FaultStatement
	 *     Element returns FaultStatement
	 *
	 * Constraint:
	 *     (name=ID str=STRING? faultDefName=NestedDotID faultDefinitions+=FaultSubcomponent*)
	 */
	protected void sequence_SpecStatement(ISerializationContext context, FaultStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SpecStatement returns HWFaultStatement
	 *     Element returns HWFaultStatement
	 *
	 * Constraint:
	 *     (name=ID str=STRING? faultDefinitions+=HWFaultSubcomponent*)
	 */
	protected void sequence_SpecStatement(ISerializationContext context, HWFaultStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SpecStatement returns PropagateStatement
	 *     Element returns PropagateStatement
	 *
	 * Constraint:
	 *     (
	 *         srcFaultList+=ID 
	 *         srcComp_path+=NestedDotID 
	 *         (srcFaultList+=ID srcComp_path+=NestedDotID)* 
	 *         destFaultList+=ID 
	 *         destComp_path+=NestedDotID 
	 *         (destFaultList+=ID destComp_path+=NestedDotID)*
	 *     )
	 */
	protected void sequence_SpecStatement(ISerializationContext context, PropagateStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     TemporalConstraint returns PermanentConstraint
	 *
	 * Constraint:
	 *     {PermanentConstraint}
	 */
	protected void sequence_TemporalConstraint(ISerializationContext context, PermanentConstraint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     TemporalConstraint returns TransientConstraint
	 *
	 * Constraint:
	 *     {TransientConstraint}
	 */
	protected void sequence_TemporalConstraint(ISerializationContext context, TransientConstraint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     TriggerCondition returns EnablerCondition
	 *
	 * Constraint:
	 *     (exprList+=Expr exprList+=Expr*)
	 */
	protected void sequence_TriggerCondition(ISerializationContext context, EnablerCondition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
