/*
 * generated by Xtext
 */
package org.xtext.example.safety.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class SafetyProposalProvider extends org.xtext.example.safety.ui.contentassist.AbstractSafetyProposalProvider {

}
