/*
 * generated by Xtext
 */
package edu.umn.cs.crisys.safety;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SafetyRuntimeModule extends edu.umn.cs.crisys.safety.AbstractSafetyRuntimeModule {

}
