/*
 * generated by Xtext
 */
package org.xtext.example.safety.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.safety.ui.internal.SafetyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SafetyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SafetyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SafetyActivator.getInstance().getInjector(SafetyActivator.ORG_XTEXT_EXAMPLE_SAFETY_SAFETY);
	}
	
}
